// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7_abSm4e1i3m1V5tcE5dAaaSD1iFVa84',
    appId: '1:292468877329:web:14d0488246228baf3ae9b0',
    messagingSenderId: '292468877329',
    projectId: 'collabworld-8b909',
    authDomain: 'collabworld-8b909.firebaseapp.com',
    storageBucket: 'collabworld-8b909.firebasestorage.app',
    measurementId: 'G-XYMMECZEWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7YahNPd-5cu-z2fOvu8ho9abTsuiuxM',
    appId: '1:292468877329:android:76f21f8bb807c3bd3ae9b0',
    messagingSenderId: '292468877329',
    projectId: 'collabworld-8b909',
    storageBucket: 'collabworld-8b909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplS3LX9-uaVFwzsCZT3eB-gBgxcR4PkE',
    appId: '1:292468877329:ios:56627c20c40adb603ae9b0',
    messagingSenderId: '292468877329',
    projectId: 'collabworld-8b909',
    storageBucket: 'collabworld-8b909.firebasestorage.app',
    iosBundleId: 'com.example.collabworldUiDesign',
  );
}
